version: '3.8'

services:
  product-service:
    image: product-service
    ports:
      - "8084:8084"
    build:
      context: ./product-service
      dockerfile: ./Dockerfile
    container_name: product-service-gbc
    environment:
      SPRING_PROFILES_ACTIVE: docker
